create extension if not exists pgcrypto;
create extension if not exists pg_trgm;

create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
create or replace function public.normalize_email(value text) returns text language sql immutable as $$ select nullif(lower(trim(value)), '') $$;
create or replace function public.normalize_phone(value text) returns text language sql immutable as $$ select nullif(regexp_replace(coalesce(value,''), '\\D', '', 'g'), '') $$;
create or replace function public.normalize_domain(value text) returns text language sql immutable as $$ select nullif(regexp_replace(regexp_replace(lower(trim(value)), '^https?://', ''), '^www\\.', ''), '') $$;

create table public.leads (
 id uuid primary key default gen_random_uuid(), first_name text, last_name text, business_name text not null, email text not null, normalized_email text generated always as (public.normalize_email(email)) stored, phone text, normalized_phone text generated always as (public.normalize_phone(phone)) stored, website text, normalized_domain text generated always as (split_part(public.normalize_domain(website), '/', 1)) stored, city text, state text, lead_source text, campaign_variant text, status text not null default 'new' check (status in ('new','hot','contacted','booked','won','lost','suppressed')), consent_email boolean not null default false, consent_sms boolean not null default false, attribution jsonb not null default '{}'::jsonb, last_activity_at timestamptz not null default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(normalized_email));
create table public.assessment_sessions (id uuid primary key default gen_random_uuid(), lead_id uuid references public.leads(id) on delete set null, resume_token_hash text not null unique, status text not null default 'started' check (status in ('started','contact_captured','completed','abandoned','expired')), answers jsonb not null default '{}'::jsonb, attribution jsonb not null default '{}'::jsonb, expires_at timestamptz not null default (now()+ interval '30 days'), last_activity_at timestamptz not null default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.assessments (id uuid primary key default gen_random_uuid(), lead_id uuid not null references public.leads(id) on delete restrict, session_id uuid references public.assessment_sessions(id) on delete set null, answer_version text not null, answers jsonb not null, recovery_score integer not null check (recovery_score between 0 and 100), recovery_level text not null, opportunity_low numeric(12,2) not null check (opportunity_low >= 0), opportunity_high numeric(12,2) not null check (opportunity_high >= opportunity_low), confidence_score integer not null check (confidence_score between 0 and 100), confidence_level text not null, primary_leak text not null, secondary_leak text, third_leak text, recommended_package text not null, routing_score integer not null default 0, account_value_score integer not null default 0, sales_readiness_score integer not null default 0, formula_version text not null, benchmark_version text not null, original_assumptions jsonb not null, edited_assumptions jsonb, calculation_snapshot jsonb not null, submitted_at timestamptz not null default now(), created_at timestamptz not null default now());
create table public.revenue_leaks (id uuid primary key default gen_random_uuid(), assessment_id uuid not null references public.assessments(id) on delete cascade, leak_type text not null, points_earned numeric not null, points_available numeric not null check (points_available > 0), severity_ratio numeric not null check (severity_ratio between 0 and 1), severity_label text not null, estimated_low numeric(12,2) not null default 0, estimated_high numeric(12,2) not null default 0, recommendation text not null, display_order integer not null, created_at timestamptz not null default now());
create table public.lead_events (id uuid primary key default gen_random_uuid(), lead_id uuid references public.leads(id) on delete set null, assessment_id uuid references public.assessments(id) on delete set null, session_id uuid references public.assessment_sessions(id) on delete set null, event_type text not null, event_data jsonb not null default '{}'::jsonb, source text not null default 'web', occurred_at timestamptz not null default now(), created_at timestamptz not null default now());
create table public.formula_versions (version text primary key, active boolean not null default false, scoring_config jsonb not null, revenue_config jsonb not null, routing_config jsonb not null, checksum text not null, effective_at timestamptz not null, created_by uuid, created_at timestamptz not null default now());
create table public.benchmark_versions (version text primary key, active boolean not null default false, config jsonb not null, source_notes text, effective_at timestamptz not null, created_at timestamptz not null default now());
create table public.consent_records (id uuid primary key default gen_random_uuid(), lead_id uuid not null references public.leads(id) on delete cascade, session_id uuid references public.assessment_sessions(id) on delete set null, email_consent boolean not null, sms_consent boolean not null default false, consent_text_version text not null, consent_text_snapshot text not null, ip_hash text, user_agent text, submission_metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.report_links (id uuid primary key default gen_random_uuid(), assessment_id uuid not null references public.assessments(id) on delete cascade, token_hash text not null unique check (length(token_hash) >= 32), status text not null default 'active', expires_at timestamptz, download_count integer not null default 0, last_accessed_at timestamptz, created_at timestamptz not null default now());
create table public.sales_notes (id uuid primary key default gen_random_uuid(), lead_id uuid not null references public.leads(id) on delete cascade, author_id uuid not null, note text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.lead_assignments (id uuid primary key default gen_random_uuid(), lead_id uuid not null references public.leads(id) on delete cascade, owner_id uuid not null, assigned_by uuid, assigned_at timestamptz not null default now(), unassigned_at timestamptz);
create table public.integration_jobs (id uuid primary key default gen_random_uuid(), provider text not null, job_type text not null, lead_id uuid references public.leads(id) on delete set null, assessment_id uuid references public.assessments(id) on delete set null, payload jsonb not null, status text not null default 'pending' check (status in ('pending','processing','succeeded','failed','dead')), attempt_count integer not null default 0, next_attempt_at timestamptz, last_error text, idempotency_key text not null unique, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.admin_users (user_id uuid primary key, role text not null check (role in ('admin','sales_manager','sales_rep','analyst')), active boolean not null default true, created_at timestamptz not null default now());

create unique index formula_one_active on public.formula_versions(active) where active;
create unique index benchmark_one_active on public.benchmark_versions(active) where active;
create index leads_email_idx on public.leads(normalized_email); create index leads_domain_idx on public.leads(normalized_domain); create index leads_phone_idx on public.leads(normalized_phone); create index leads_business_trgm_idx on public.leads using gin (business_name gin_trgm_ops); create index assessments_lead_submitted_idx on public.assessments(lead_id, submitted_at desc); create index assessments_score_idx on public.assessments(recovery_score desc); create index assessments_package_idx on public.assessments(recommended_package); create index lead_events_lead_idx on public.lead_events(lead_id, occurred_at desc); create index lead_events_type_idx on public.lead_events(event_type, occurred_at desc); create index integration_jobs_retry_idx on public.integration_jobs(status, next_attempt_at); create index sessions_resume_idx on public.assessment_sessions(resume_token_hash); create index report_links_token_idx on public.report_links(token_hash);

create trigger leads_updated_at before update on public.leads for each row execute function public.set_updated_at(); create trigger sessions_updated_at before update on public.assessment_sessions for each row execute function public.set_updated_at(); create trigger notes_updated_at before update on public.sales_notes for each row execute function public.set_updated_at(); create trigger jobs_updated_at before update on public.integration_jobs for each row execute function public.set_updated_at();

create or replace function public.current_admin_role() returns text language sql stable security definer set search_path=public as $$ select role from public.admin_users where user_id = auth.uid() and active limit 1 $$;
create or replace function public.is_admin_role(allowed text[]) returns boolean language sql stable security definer set search_path=public as $$ select coalesce(public.current_admin_role() = any(allowed), false) $$;
create or replace function public.upsert_lead(p_email text, p_business_name text, p_first_name text default null, p_last_name text default null, p_phone text default null, p_website text default null, p_city text default null, p_state text default null, p_attribution jsonb default '{}'::jsonb) returns uuid language plpgsql security definer set search_path=public as $$ declare v_id uuid; begin insert into public.leads(email,business_name,first_name,last_name,phone,website,city,state,attribution) values (p_email,p_business_name,p_first_name,p_last_name,p_phone,p_website,p_city,p_state,p_attribution) on conflict(normalized_email) do update set business_name=coalesce(nullif(excluded.business_name,''),leads.business_name), first_name=coalesce(excluded.first_name,leads.first_name), last_name=coalesce(excluded.last_name,leads.last_name), phone=coalesce(excluded.phone,leads.phone), website=coalesce(excluded.website,leads.website), city=coalesce(excluded.city,leads.city), state=coalesce(excluded.state,leads.state), attribution=leads.attribution || excluded.attribution, last_activity_at=now() returning id into v_id; return v_id; end; $$;
create or replace function public.record_lead_event(p_lead_id uuid, p_assessment_id uuid, p_session_id uuid, p_event_type text, p_event_data jsonb default '{}'::jsonb, p_source text default 'web') returns uuid language plpgsql security definer set search_path=public as $$ declare v_id uuid; begin insert into public.lead_events(lead_id,assessment_id,session_id,event_type,event_data,source) values(p_lead_id,p_assessment_id,p_session_id,p_event_type,p_event_data,p_source) returning id into v_id; return v_id; end; $$;
create or replace function public.get_active_formula_version() returns public.formula_versions language sql stable security definer set search_path=public as $$ select * from public.formula_versions where active limit 1 $$;
create or replace function public.generate_report_token() returns text language sql volatile as $$ select encode(gen_random_bytes(32),'hex') $$;
create or replace function public.mark_lead_hot(p_lead_id uuid) returns void language sql security definer set search_path=public as $$ update public.leads set status='hot', last_activity_at=now() where id=p_lead_id $$;
create or replace function public.deduplicate_lead_candidate(p_email text) returns uuid language sql stable security definer set search_path=public as $$ select id from public.leads where normalized_email=public.normalize_email(p_email) limit 1 $$;
create or replace function public.calculate_recovery_assessment() returns jsonb language sql stable as $$ select jsonb_build_object('implemented_in','typescript_build_3','status','placeholder') $$;

alter table public.leads enable row level security; alter table public.assessment_sessions enable row level security; alter table public.assessments enable row level security; alter table public.revenue_leaks enable row level security; alter table public.lead_events enable row level security; alter table public.formula_versions enable row level security; alter table public.benchmark_versions enable row level security; alter table public.consent_records enable row level security; alter table public.report_links enable row level security; alter table public.sales_notes enable row level security; alter table public.lead_assignments enable row level security; alter table public.integration_jobs enable row level security; alter table public.admin_users enable row level security;

create policy "Admins manage admin users" on public.admin_users for all to authenticated using (public.is_admin_role(array['admin'])) with check (public.is_admin_role(array['admin'])); -- Only active admins manage access.
create policy "Managers and admins view all leads" on public.leads for select to authenticated using (public.is_admin_role(array['admin','sales_manager'])); -- Full sales visibility.
create policy "Sales reps view assigned or hot unassigned leads" on public.leads for select to authenticated using (public.current_admin_role()='sales_rep' and (exists(select 1 from public.lead_assignments la where la.lead_id=id and la.owner_id=auth.uid() and la.unassigned_at is null) or status='hot')); -- Sales rep scoped access.
create policy "Analysts view leads" on public.leads for select to authenticated using (public.current_admin_role()='analyst'); -- Analyst app must mask contact fields.
create policy "Admins and managers modify leads" on public.leads for update to authenticated using (public.is_admin_role(array['admin','sales_manager'])) with check (public.is_admin_role(array['admin','sales_manager'])); -- Controlled lead updates.
create policy "Admin roles view sessions" on public.assessment_sessions for select to authenticated using (public.is_admin_role(array['admin','sales_manager','sales_rep','analyst'])); -- No anonymous sessions.
create policy "Admin roles view assessments" on public.assessments for select to authenticated using (public.is_admin_role(array['admin','sales_manager','sales_rep','analyst'])); -- Role-aware in app layer.
create policy "Admin roles view leaks" on public.revenue_leaks for select to authenticated using (public.is_admin_role(array['admin','sales_manager','sales_rep','analyst'])); -- Reporting access.
create policy "Admin roles view events" on public.lead_events for select to authenticated using (public.is_admin_role(array['admin','sales_manager','analyst'])); -- Event data restricted from reps.
create policy "Admins manage formulas" on public.formula_versions for all to authenticated using (public.is_admin_role(array['admin'])) with check (public.is_admin_role(array['admin'])); -- Formula config admin-only.
create policy "Admin roles view formulas" on public.formula_versions for select to authenticated using (public.is_admin_role(array['admin','sales_manager','analyst'])); -- No anonymous formula reads.
create policy "Admins manage benchmarks" on public.benchmark_versions for all to authenticated using (public.is_admin_role(array['admin'])) with check (public.is_admin_role(array['admin'])); -- Benchmark config admin-only.
create policy "Admin roles view benchmarks" on public.benchmark_versions for select to authenticated using (public.is_admin_role(array['admin','sales_manager','analyst'])); -- No anonymous benchmark reads.
create policy "Admins view consent records" on public.consent_records for select to authenticated using (public.is_admin_role(array['admin','sales_manager'])); -- Analysts excluded from raw consent/contact proof.
create policy "Admin roles view report links" on public.report_links for select to authenticated using (public.is_admin_role(array['admin','sales_manager'])); -- Tokens stay hashed.
create policy "Admins manage notes" on public.sales_notes for all to authenticated using (public.is_admin_role(array['admin','sales_manager','sales_rep'])) with check (public.is_admin_role(array['admin','sales_manager','sales_rep'])); -- Sales notes by active sales roles.
create policy "Admins manage assignments" on public.lead_assignments for all to authenticated using (public.is_admin_role(array['admin','sales_manager'])) with check (public.is_admin_role(array['admin','sales_manager'])); -- Assignment control.
create policy "Admins manage integration jobs" on public.integration_jobs for all to authenticated using (public.is_admin_role(array['admin'])) with check (public.is_admin_role(array['admin'])); -- Integration retries are admin-only.

insert into public.formula_versions(version,active,scoring_config,revenue_config,routing_config,checksum,effective_at) values ('medspa-v1.0.0',true,'{"max_score":100,"score_bands":[[0,24,"Strong foundation"],[25,49,"Moderate revenue leakage"],[50,74,"Significant revenue leakage"],[75,100,"Critical recovery opportunity"]],"questions":["location_count_band","monthly_inquiry_band","average_value_band","missed_call_handling","digital_response_time","after_hours_coverage","inquiry_booking_rate_band","unbooked_lead_followup","no_show_rate_band","missed_appointment_recovery","treatment_recall_process","reactivation_process","membership_package_maturity","review_request_process","reporting_visibility"]}'::jsonb,'{"principles":["conservative","no_double_counting","server_side"],"components":["missed_slow_inquiry","unbooked_consultation","no_show_recovery","treatment_recall","dormant_reactivation"],"overlap_adjustment":{"low":0.80,"high":0.85},"caps":{"low":0.25,"high":0.40},"rounding":[100,500,1000]}'::jsonb,'{"packages":{"recovery_system":{"price":599,"setup":"750-1000"},"ai_revenue_command_center":{"price":999,"setup":"1250-1500"}},"primary_recommendation_only":true}'::jsonb,'seed-medspa-v1.0.0',now());
insert into public.benchmark_versions(version,active,config,source_notes,effective_at) values ('medspa-benchmark-v1.0.0',true,'{"confidence_bands":{"high":[80,100],"medium":[60,79],"directional":[0,59]},"severity_bands":{"low":[0,0.24],"moderate":[0.25,0.49],"high":[0.50,0.74],"critical":[0.75,1]}}'::jsonb,'Approved V1 benchmark seed configuration',now());
